insert into dbo.store (store_name, city, states) values ('Ironworker', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Terrazzo', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Millwright', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Refridgeration', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Terrazzo', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Boilermaker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipelayer', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Millwright', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Glazier', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Stucco Mason', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Carpenter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Linemen', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Stucco Mason', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Refridgeration', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipelayer', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Glazier', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Electrician', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Stucco Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Millwright', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Glazier', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Refridgeration', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Millwright', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Carpenter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plasterers', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plasterers', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Carpenter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Glazier', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Electrician', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Refridgeration', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Linemen', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Glazier', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Linemen', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plasterers', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Terrazzo', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Terrazzo', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Boilermaker', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Millwright', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Boilermaker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Refridgeration', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipelayer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Millwright', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Linemen', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plasterers', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Terrazzo', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Refridgeration', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plasterers', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Refridgeration', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Boilermaker', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Terrazzo', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Terrazzo', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Electrician', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Terrazzo', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Boilermaker', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plasterers', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Terrazzo', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Terrazzo', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Linemen', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Millwright', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Electrician', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Glazier', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Linemen', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Electrician', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Refridgeration', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Carpenter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipelayer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Millwright', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Terrazzo', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Electrician', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Millwright', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipelayer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Refridgeration', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Stucco Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Terrazzo', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Electrician', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipelayer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Electrician', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Linemen', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plasterers', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plasterers', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipelayer', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Glazier', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Linemen', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Electrician', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Carpenter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipelayer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Stucco Mason', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Carpenter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Carpenter', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Linemen', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Glazier', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Electrician', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Stucco Mason', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Millwright', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Glazier', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Refridgeration', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Refridgeration', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipelayer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Carpenter', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Electrician', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Boilermaker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Glazier', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Glazier', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Terrazzo', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Glazier', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Boilermaker', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipelayer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Stucco Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Stucco Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Boilermaker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Electrician', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Boilermaker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Electrician', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Carpenter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plasterers', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Terrazzo', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Glazier', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Linemen', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Millwright', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Millwright', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Stucco Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Stucco Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Terrazzo', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Linemen', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Millwright', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Boilermaker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Terrazzo', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Millwright', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Glazier', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Linemen', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Terrazzo', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Stucco Mason', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plasterers', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plasterers', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Boilermaker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Carpenter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Boilermaker', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipelayer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Terrazzo', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipelayer', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Linemen', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipelayer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plasterers', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Refridgeration', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipelayer', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Stucco Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Stucco Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Millwright', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Terrazzo', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipelayer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Millwright', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Terrazzo', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Terrazzo', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Stucco Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plasterers', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Glazier', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Glazier', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Boilermaker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipelayer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Linemen', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Boilermaker', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Boilermaker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Electrician', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plasterers', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Stucco Mason', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Refridgeration', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plasterers', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Boilermaker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plasterers', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Millwright', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Refridgeration', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Millwright', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Carpenter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Linemen', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Refridgeration', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Terrazzo', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Stucco Mason', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Electrician', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Millwright', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Electrician', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Electrician', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Terrazzo', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Boilermaker', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Boilermaker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipelayer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plasterers', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Carpenter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Boilermaker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Linemen', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Carpenter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Boilermaker', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Carpenter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Stucco Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Stucco Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Refridgeration', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plasterers', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Millwright', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Glazier', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Glazier', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Stucco Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Terrazzo', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipelayer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plasterers', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Millwright', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Glazier', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plasterers', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Millwright', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Millwright', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Linemen', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Carpenter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipelayer', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Glazier', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Refridgeration', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Glazier', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Linemen', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Terrazzo', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Refridgeration', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Boilermaker', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Stucco Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Glazier', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Refridgeration', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Millwright', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plasterers', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipelayer', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plasterers', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Stucco Mason', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Boilermaker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Boilermaker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Linemen', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Electrician', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Carpenter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipelayer', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Linemen', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Boilermaker', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Electrician', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plasterers', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Glazier', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Millwright', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Linemen', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Electrician', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Millwright', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Linemen', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Terrazzo', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Electrician', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Terrazzo', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Electrician', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Linemen', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Boilermaker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Stucco Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Refridgeration', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Refridgeration', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Glazier', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Stucco Mason', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Millwright', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Electrician', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Glazier', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Refridgeration', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Terrazzo', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Carpenter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Carpenter', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plasterers', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Carpenter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Millwright', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Boilermaker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipelayer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Boilermaker', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Terrazzo', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Millwright', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Refridgeration', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Refridgeration', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipelayer', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Linemen', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Electrician', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Refridgeration', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Terrazzo', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plasterers', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Stucco Mason', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plasterers', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Glazier', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Linemen', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Carpenter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Electrician', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Stucco Mason', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipelayer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Boilermaker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Glazier', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Carpenter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Millwright', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Refridgeration', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Linemen', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Boilermaker', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Glazier', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Millwright', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Linemen', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Carpenter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Carpenter', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Refridgeration', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Glazier', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Electrician', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Stucco Mason', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Terrazzo', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Electrician', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Stucco Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Glazier', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Carpenter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Carpenter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Boilermaker', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipelayer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Electrician', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Boilermaker', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Linemen', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Stucco Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Carpenter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Glazier', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plasterers', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Carpenter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Refridgeration', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Terrazzo', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Boilermaker', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Electrician', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plasterers', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Stucco Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Glazier', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipelayer', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Carpenter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Stucco Mason', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Stucco Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Glazier', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Terrazzo', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Boilermaker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Terrazzo', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('HVAC', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Linemen', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Electrician', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Carpenter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Stucco Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plasterers', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Glazier', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Carpenter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Concrete Finisher', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Carpenter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Electrician', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plumber', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Carpenter', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Electrician', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Millwright', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Tile Setter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Welder', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Painter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Stucco Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plasterers', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Boilermaker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Pipefitter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Refridgeration', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Landscaper', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Waterproofer', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Sheet Metal Worker', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Cement Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Stucco Mason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Ironworker', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Linemen', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Equipment Operator', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Refridgeration', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Plasterers', 'Fairbanks', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Safety Officer', 'Juneau', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Brickmason', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Carpenter', 'Anchorage', 'Alaska');
insert into dbo.store (store_name, city, states) values ('Laborer', 'Juneau', 'Alaska');
