insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (1, 'Appetizer - Chicken Satay', 1, 1, null);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (2, 'Pesto - Primerba, Paste', 2, 2, 947);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (3, 'Spice - Pepper Portions', 3, 3, 775);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (4, 'Bread - Pita, Mini', 4, 4, null);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (5, 'Tray - Foam, Square 4 - S', 5, 5, null);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (6, 'Wine - Cave Springs Dry Riesling', 6, 6, 382);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (7, 'Beef - Top Sirloin - Aaa', 7, 7, 136);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (8, 'Squash - Acorn', 8, 8, 275);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (9, 'Coffee - Irish Cream', null, 9, 810);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (10, 'French Pastry - Mini Chocolate', 10, 10, 903);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (11, 'Beef - Ground Medium', 11, 11, 981);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (12, 'Water - Evian 355 Ml', 12, 12, null);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (13, 'Chicken - Breast, 5 - 7 Oz', 13, 13, 366);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (14, 'Cheese - Cottage Cheese', 14, null, 96);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (15, 'Ice Cream Bar - Drumstick', 15, 15, null);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (16, 'Wine - Periguita Fonseca', 16, 16, 213);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (17, 'Mace Ground', null, 17, 456);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (18, 'Spice - Peppercorn Melange', 18, 18, null);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (19, 'Appetizer - Lobster Phyllo Roll', 19, 19, 202);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (20, 'Tandoori Curry Paste', null, 20, 125);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (21, 'Muffin Batt - Blueberry Passion', 21, 21, 688);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (22, 'Tea - Herbal - 6 Asst', 22, 22, 563);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (23, 'Juice - Propel Sport', 23, 23, 907);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (24, 'Napkin White - Starched', 24, 24, 189);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (25, 'Shrimp - 150 - 250', 25, null, null);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (26, 'Bag - Bread, White, Plain', 26, null, null);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (27, 'Soup - Verve - Chipotle Chicken', 27, 27, 787);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (28, 'Yeast Dry - Fermipan', 28, 28, 45);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (29, 'Curry Powder', 29, 29, 930);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (30, 'Oil - Hazelnut', 30, 30, 285);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (31, 'Ostrich - Prime Cut', 31, 31, 857);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (32, 'Beef - Tongue, Cooked', 32, 32, null);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (33, 'Pea - Snow', 33, 33, 676);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (34, 'Juice - Ocean Spray Cranberry', 34, null, null);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (35, 'Yogurt - Cherry, 175 Gr', 35, 35, 246);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (36, 'Crackers - Soda / Saltins', 36, 36, null);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (37, 'Wine - Sogrape Mateus Rose', 37, 37, 680);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (38, 'Beans - Long, Chinese', 38, null, 872);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (39, 'Tea - Orange Pekoe', 39, 39, null);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (40, 'Butter - Salted, Micro', 40, 40, 526);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (41, 'Baking Powder', 41, 41, null);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (42, 'Appetizer - Sausage Rolls', 42, 42, null);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (43, 'Pork - Backs - Boneless', 43, null, 387);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (44, 'Turkey - Ground. Lean', 44, 44, 270);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (45, 'Spring Roll Wrappers', null, 45, 659);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (46, 'Bread - Assorted Rolls', 46, null, null);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (47, 'Rosemary - Fresh', 47, null, null);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (48, 'Chicken - Breast, 5 - 7 Oz', 48, 48, 43);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (49, 'Muffin - Mix - Mango Sour Cherry', null, 49, 562);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (50, 'Table Cloth - 53x69 Colour', 50, 50, null);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (51, 'Pickles - Gherkins', 51, 51, 75);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (52, 'V8 Splash Strawberry Kiwi', 52, 52, 924);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (53, 'Turkey - Whole, Fresh', null, 53, null);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (54, 'Shark - Loin', 54, null, 56);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (55, 'Hinge W Undercut', 55, 55, 234);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (56, 'Sprouts - Baby Pea Tendrils', 56, 56, 921);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (57, 'Sloe Gin - Mcguinness', 57, 57, 806);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (58, 'Tomatoes - Heirloom', null, 58, 38);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (59, 'Sauce - Vodka Blush', 59, null, 881);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (60, 'Wine - Fat Bastard Merlot', 60, 60, 507);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (61, 'Cheese - Shred Cheddar / Mozza', 61, 61, 193);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (62, 'Mushroom - Trumpet, Dry', 62, 62, 123);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (63, 'Cookie Dough - Oatmeal Rasin', 63, 63, 480);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (64, 'Appetizer - Crab And Brie', 64, null, 446);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (65, 'Water, Tap', null, 65, 198);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (66, 'Sugar Thermometer', 66, null, 556);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (67, 'Pasta - Agnolotti - Butternut', 67, 67, 457);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (68, 'Plasticspoonblack', 68, 68, 77);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (69, 'Yogurt - Cherry, 175 Gr', 69, 69, null);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (70, 'Wine - Guy Sage Touraine', 70, null, 552);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (71, 'V8 - Vegetable Cocktail', 71, 71, 77);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (72, 'Apple - Royal Gala', 72, 72, null);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (73, 'Boogies', 73, 73, 921);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (74, 'Vanilla Beans', null, null, 278);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (75, 'Chinese Foods - Cantonese', 75, 75, null);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (76, 'Chinese Foods - Chicken Wing', 76, 76, 567);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (77, 'Aspic - Light', 77, 77, 450);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (78, 'Veal - Inside, Choice', 78, null, 747);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (79, 'Rambutan', 79, 79, 932);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (80, 'Bread - Pumpernickel', 80, 80, 438);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (81, 'Beef - Short Ribs', 81, null, null);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (82, 'Cardamon Seed / Pod', 82, null, 477);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (83, 'Cheese - Cheddarsliced', null, 83, 859);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (84, 'Wheat - Soft Kernal Of Wheat', 84, 84, null);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (85, 'Plastic Wrap', 85, 85, 63);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (86, 'Lamb - Whole Head Off', 86, 86, 987);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (87, 'Cheese - Mozzarella', null, 87, 516);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (88, 'Yams', 88, 88, 456);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (89, 'Turkey - Breast, Boneless Sk On', null, 89, null);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (90, 'Beer - Sleeman Fine Porter', 90, 90, null);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (91, 'Shrimp, Dried, Small / Lb', 91, 91, 408);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (92, 'Pastry - Lemon Danish - Mini', 92, 92, 572);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (93, 'Peach - Halves', 93, 93, 256);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (94, 'Wine - Barossa Valley Estate', 94, 94, 111);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (95, 'Peas - Pigeon, Dry', 95, 95, 915);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (96, 'Sproutsmustard Cress', 96, 96, 950);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (97, 'Sugar - Splenda Sweetener', 97, 97, 665);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (98, 'White Fish - Filets', 98, 98, 361);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (99, 'Cake - Box Window 10x10x2.5', 99, null, null);
insert into dbo.product_order_item (order_id, product_name, category, stock_quantity, price) values (100, 'Chilli Paste, Ginger Garlic', 100, null, 852);
